version: '3.8'
services:
  mongo:
    container_name: mongodb-cartservice
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  redis:
    container_name: redis-cartservice
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo-data:

