spring:
  application:
    name: cartservice

  data:
    mongodb:
      host: localhost
      port: 27017
      database: cartservice
    redis:
      host: localhost
      port: 6379
      password: sa

  cache:
    redis:
      time-to-live: 6000
